[jobs.build-debug]
command = ["cmd.exe", "/c", "build.bat", "debug"]
need_stdout = true
allow_warnings = true
watch = [".rust/src"]

[jobs.build-release]
command = ["cmd.exe", "/c", "build.bat", "release"]
need_stdout = true
allow_warnings = true
watch = [".rust/src"]

[jobs.clippy]
command = ["cargo", "clippy", "--manifest-path", ".rust/Cargo.toml", "--all-targets", "--all-features", "--", "-D", "warnings"]
need_stdout = false
watch = [".rust/src"]

[jobs.check]
command = ["cargo", "check", "--manifest-path", ".rust/Cargo.toml", "--all-targets", "--", "-j", "12"]
watch = [".rust/src"]
